language: python
python:
  - "3.4"
  - "3.5"
install:
  - pip install coveralls
  - pip install sphinx
  - pip install sphinx_rtd_theme
  - pip install pypandoc
script:
  - coverage run --source=galactic setup.py test
after_success:
  - coveralls
